### ISSUE TITLE
Add RentCafe to list of Vendors

### ISSUE THREAD

**Issue by colabottles** [karlgroves/overlayfactsheet#1015]
[RentCafe](https://www.rentcafe.com/) has their own overlay they use on sites I have noticed from some research I have been doing. [You can see it in action here](https://www.s29apartments.com/accessibility).

Looks as if it is under [Yardi](https://www.yardi.com/services/) which does property management which is a highly hit space as far as the overlay companies goe.

**Comment by karlgroves** [comment]
@colabottles can you find another example of it in action? The link you put in your original comment is broken

**Comment by karlgroves** [comment]
Quick note: after investigation, it does not look like this is a white-labelled/ rebranded widget. Looks to be created/ owned/ managed by RentCafe.

Will add this to the list on next updates
