### ISSUE TITLE
Adding translations

### ISSUE THREAD

**Issue by mfru** [karlgroves/overlayfactsheet#1087]
Was adding translations considered so far? (didn't find references in open or closed issues)

I am willing to contribute a German translation if wanted.

**Comment by karlgroves** [comment]
Max, thanks for volunteering to do a translation! 
Someone else had mentioned doing a French version as well.

The bigger challenge, however, isn't the translation but how we'd serve that up.  Do you have any thoughts on that?  I'm thinking basic content negotiation, assuming I can set that up on Netlify

**Comment by mfru** [comment]
Karl, from the top of my head since you mentioned basic content negotiation you could go for `index.<LANGUAGE_CODE>.html` and serve appropriately, but I guess that would mean lots of duplication. (Linear for every added language).

Maintenance will be quite hard once the project has more than let's say 4 languages. At that point it will make sense to think of templating and generating the content with a static site generator with support for translation and internationalization.

**Comment by karlgroves** [comment]
Resolved by #1143
