### ISSUE TITLE
Add a max-width to keep line length readable

### ISSUE THREAD

**Issue by stringyland** [karlgroves/overlayfactsheet#110]
I'm not sure what the long-term plan is for the design of the site, but in the short term adding a max-width to the body or to <p> tags would help a lot with readability.

**Comment by yatil** [comment]
There is a 60rem max-width: https://github.com/karlgroves/overlayfactsheet/blob/f4357896141e143e7afb8275cb108f7ad928060c/src/index.html#L38

**Comment by stringyland** [comment]
Love that new line-length!
