### ISSUE TITLE
Add DearDoc to list of overlay vendors

### ISSUE THREAD

**Issue by colabottles** [karlgroves/overlayfactsheet#1121]
There is a site, https://mbswellness.org/ that uses an overlay that is by DearDoc: https://www.getdeardoc.com/

Yet another overlay and yet another overlay company. This targets the medical field and they have recorded testimonials. Probably so they don't get caught doing what accessiBe did with the fake profiles, testimonials, and such.

This should probably go on the list as well.

**Comment by cstrobbe** [comment]
As far as I can see, the site does not claim that the DearDoc widget automatically solves all accessibility issues. 
I'm not saying the widget is a good solution (for example, if you enable the "Cognitive" profile on mbswellness.org, you get to see CSS code; see screenshot), but the focus seems to be more on getting more patients than automatically meeting accessibility requirements.

![Webpage displaying CSS code instead of readable content](https://github.com/karlgroves/overlayfactsheet/assets/1943277/50787a10-b716-48e8-b743-169d923f6c63)

**Comment by colabottles** [comment]
An overlay is an overlay. Until I see demonstrated proof these work as they are claimed to or "intended", I have them in my sights. What @karlgroves wants to do from here is up to the repo owner.

For the record, I didn't see DearDoc claim it solves all accessibility issues, nor did I state they did. But what tests I did, it didn't do anything to improve the accessibility of the site. Therefore, to me, it's an overlay plain and simple.

**Comment by cstrobbe** [comment]
>An overlay is an overlay. Until I see demonstrated proof these work as they are claimed to or "intended", I have them in my sights. 

As far as I know, this is repository is about accessibility overlays that vendors promote with false claims. In order to help Karl Groves, can you please document the false accessibility-related claims made by DearDoc?

**Comment by colabottles** [comment]
> > An overlay is an overlay. Until I see demonstrated proof these work as they are claimed to or "intended", I have them in my sights.
> 
> As far as I know, this is repository is about accessibility overlays that vendors promote with false claims. In order to help Karl Groves, can you please document the false accessibility-related claims made by DearDoc?

https://www.getdeardoc.com/solutions/ada-compliance-tool - Now correct me if I'm wrong but an overlay does not fix "ADA compliance". I'm going to defer to Karl from here because I'm not going to, nor do I have time to have a back-and-forth about semantics. Karl knows how I feel and where I stand on these "tools".

**Comment by karlgroves** [comment]
On further inspection, it appears that Deardoc is merely reselling Equally.ai, which is already listed.

For clarity on the other aspects of this thread, this repo is about any overlay. 

However, if anyone wants to assist on the false claims aspect, I do have another repo relating to the [OverlayFalseClaims.com](https://overlayfalseclaims.com/) website.

**Comment by karlgroves** [comment]
Closing for now. Feel free to re-open or comment if anyone disagrees
