### ISSUE TITLE
Add Article from FT

### ISSUE THREAD

**Issue by karlgroves** [karlgroves/overlayfactsheet#1188]
https://archive.is/MRhll

**Comment by janmaarten-a11y** [comment]
May already be on your radar, but some helpful context for this one around the source and potential astroturfing:

- https://mastodon.social/@aardrian@toot.cafe/112254279579011070
- https://mastodon.social/@aardrian@toot.cafe/112254300326402432

**Comment by janmaarten-a11y** [comment]
@aardrian Ah, yes! Thank you. Those were links from my own feed, not your original posts.
