### ISSUE TITLE
Add link to site URL in README and/or the repository's 'About' section

### ISSUE THREAD

**Issue by jfhector** [karlgroves/overlayfactsheet#188]
#### Usability issue

I was on the repository page, and I wanted to see the deployed site.
But I couldn't remember the URL.

#### Suggested improvement

Add link to https://overlayfactsheet.com/ in the repository's README and/or 'About' section

#### Also

Thanks for having created this site.

**Comment by karlgroves** [comment]
Fixed. Thanks!
