### ISSUE TITLE
More overlays to list

### ISSUE THREAD

**Issue by karlgroves** [karlgroves/overlayfactsheet#281]
* adally
* adaptemonweb (Adapt my Web)
* Lisio
* Allyable
* ReciteME
* Sogo
* TruAbilities
* True Accessibility
* Accessiblelink
* FACIL'iti

This list is probably going to grow.  

Right now we mention overlays by name in two places.  I'm wondering if there might need to be some revisions to the content so those in-content lists of names don't make the page unweildy for users?

**Comment by okeul** [comment]
@karlgroves I guess you can close this issue.

**Comment by karlgroves** [comment]
Closing They've been added
