### ISSUE TITLE
Add Signature - Shaylor Murray

### ISSUE THREAD

**Issue by growthdyn-luke** [karlgroves/overlayfactsheet#434]
I would like to add the signature "Shaylor Murray, Owner and Product Developer, Online ADA (Max Access)"

**Comment by shaylor-murray** [comment]
Could we please get this added to the website? 

"Shaylor Murray, Owner and Product Developer, Online ADA (Max Access)"

Thanks!

**Comment by karlgroves** [comment]
Closing. Will not be adding signature from the owner of a company who makes an overlay, as it is counter to the point.
