### ISSUE TITLE
Web accessibility overlay tools: lies and gum balls url

### ISSUE THREAD

**Issue by jlukosky** [karlgroves/overlayfactsheet#490]
The link to "Web accessibility overlay tools: lies and gum balls" is currently listed as:

href="lalutineduweb.fr/en/web-accessibility-overlays-lies-gum-balls/"

which tries to open a relative URL. It should be correct to:

href="https://www.lalutineduweb.fr/en/web-accessibility-overlays-lies-gum-balls/"

**Comment by karlgroves** [comment]
Thanks for the heads up!
