### ISSUE TITLE
A bit unrelated, but how would you determine programatically that a site is using an overlay?

### ISSUE THREAD

**Issue by mgifford** [karlgroves/overlayfactsheet#615]
Is there code out there to determine easily if AccessiBe, AudioEye or others are being used? Ultimately, what is their JS file I suppose, and can you parse it from the page source.

**Comment by karlgroves** [comment]
@mgifford IDK if anyone has done such a thing, but you're on the right track. Just find the domain(s) from which their script is served and then add that to whatever you're using to track such a thing
