### ISSUE TITLE
Add Three Signatories

### ISSUE THREAD

**Issue by dbseagull** [karlgroves/overlayfactsheet#904]
First, thank you for doing this. It's obviously important.

Please add three signatories to the list. Thank you.

Jack Asliev, CPACC, QA & Accessibility Analyst
Danielli Franquim, CPACC, QA & Accessibility Analyst
Daniel Seagull, CPACC, QA & Accessibility Analyst

**Comment by karlgroves** [comment]
@dbseagull can you please have Jack and Danielli comment here with their permission to be added?

**Comment by dbseagull** [comment]
Thank you, Karl. I have their permission in my email but that doesn't do you much good! I'll ask them to sign on and add comments here.

**Comment by Elli360** [comment]
Thanks Dan! 

Hi Karl, Here is my signature, 
Danielli Franquim, CPACC, QA & Accessibility Analyst

Thank you for doing this!

**Comment by karlgroves** [comment]
@dbseagull @Elli360 Thanks! Please have Jack comment here as well.

Sorry to be a stickler on this, but I don't want any overlay companies coming around to say that any of these names are fake or added against people's will.

**Comment by dbseagull** [comment]
You're right to be a stickler. Let's abandon him from this. You have my permission and you've got Danielli's. Do you need us to close this issue and create new ones? Shall I just edit the issue to remove his name? What do you need me to do to ensure everything is on the up-and-up?
Thanks again.

**Comment by karlgroves** [comment]
@dbseagull I'll add the 2. No need for another issue.  Thanks for understanding.
